#!/usr/bin/env sh

[ -z "$1" ] && exit 1

SNAPSHOT_DEST="$HOME"/.local/share/aur/snapshot
PACKAGE_DEST="$HOME"/.local/share/aur/package

## makepkg vars
export PKGDEST="$PACKAGE_DEST"
export SRCDEST="/tmp/makepkg/src"
export SRCPKGDEST="/tmp/makepkg/build"

_aur_help() {
    /usr/bin/echo "Usage:"
    /usr/bin/echo "  ${0##*/} <NAME> [NAME1] [NAME2]   Install packages in order"
    /usr/bin/echo "  ${0##*/} -cp                      Clear packages cache"
    /usr/bin/echo "  ${0##*/} -cs                      Clear snapshots cache"
    /usr/bin/echo "  ${0##*/} -h                       Show this help"
}

_aur_install() {
    [ -d "$SNAPSHOT_DEST" ] || /usr/bin/mkdir -p "$SNAPSHOT_DEST"
    [ -d "$PKGDEST" ] || /usr/bin/mkdir -p "$PKGDEST"
    [ -d "$SRCDEST" ] || /usr/bin/mkdir -p "$SRCDEST"
    [ -d "$SRCPKGDEST" ] || /usr/bin/mkdir -p "$SRCPKGDEST"

    PACKAGE_NAME=$1
    if [ -n "$PACKAGE_NAME" ]; then
        # clear previous snapshot if exists
        [ -d "$SNAPSHOT_DEST/$PACKAGE_NAME" ] &&
            /usr/bin/rm -r "${SNAPSHOT_DEST:?}/${PACKAGE_NAME:?}"

        # download snapshot and build using makepkg
        cd "$SNAPSHOT_DEST" &&
            /usr/bin/curl -Of "https://aur.archlinux.org/cgit/aur.git/snapshot/$PACKAGE_NAME.tar.gz" &&
            /usr/bin/tar -xzf "$PACKAGE_NAME.tar.gz" &&
            cd "$PACKAGE_NAME" &&
            /usr/bin/makepkg --install --syncdeps --rmdeps --clean
    fi
}

_aur_clear_packages() {
    [ -d "$PKGDEST" ] && paccache -c "$PKGDEST"
}

_aur_clear_snapshots() {
    [ -d "$SNAPSHOT_DEST" ] && /usr/bin/rm -r "${SNAPSHOT_DEST:?}"
}

case "$1" in
-cs)
    _aur_clear_snapshots
    ;;
-cp)
    _aur_clear_packages
    ;;
-h)
    _aur_help
    ;;
*)
    for arg in "$@"; do
        _aur_install "$arg"
    done
    ;;
esac
