#!/usr/bin/env bash

[ -z "$EDITOR" ] && export EDITOR=/usr/bin/nano
[ -z "$CHEAT_PATH" ] && export CHEAT_PATH="$XDG_CONFIG_HOME"/cheat

_cheat_help() {
    /usr/bin/echo "Usage:"
    /usr/bin/echo "  ${0##*/}                          List available cheats"
    /usr/bin/echo "  ${0##*/} <NAME>                   Show cheat by NAME"
    /usr/bin/echo "  ${0##*/} -e <NAME>                Edit cheat by NAME"
    /usr/bin/echo "  ${0##*/} -r <NAME>                Remove cheat by NAME"
    /usr/bin/echo "  ${0##*/} -h                       Show this help"
}

_cheat_list() {
    /usr/bin/ls -1A -I '.*' "$CHEAT_PATH"
}

_cheat_show() {
    [ -z "$1" ] && exit 1
    CHEAT="$CHEAT_PATH"/"$1"
    if [ -r "$CHEAT" ]; then
        /usr/bin/awk \
            -v dim="$(tput dim)" \
            -v reset="$(tput sgr0)" \
            'BEGIN {
                is_first_line=1;
                is_front_matter=0;
            }
            /^---$/ {
                if (is_first_line) {
                    is_front_matter=1;
                }
            }
            {
                if (! is_front_matter) {
                    if ($1 == "#") {
                        printf "%s%s%s\n", dim, $0, reset;
                    } else {
                        print $0;
                    }
                }
            }
            /^(---)$/ {
                if (! is_first_line) {
                    is_front_matter=0;
                }
                is_first_line=0;
            }' \
            <"$CHEAT"
    fi
}

_cheat_edit() {
    [ -z "$1" ] && exit 1
    [ -d "$CHEAT_PATH" ] || /usr/bin/mkdir -p
    $EDITOR "$CHEAT_PATH"/"$1"
}

_cheat_remove() {
    [ -z "$1" ] && exit 1
    /usr/bin/rm "$CHEAT_PATH"/"$1"
}

case "$1" in
-h)
    _cheat_help
    ;;
-e)
    if [ -z "$2" ]; then
        _cheat_help
        exit 1
    fi
    _cheat_edit "$2"
    ;;
-r)
    if [ -z "$2" ]; then
        _cheat_help
        exit 1
    fi
    _cheat_remove "$2"
    ;;
*)
    if [ -z "$1" ]; then
        _cheat_list
        exit
    fi
    _cheat_show "$1"
    ;;
esac
