#!/usr/bin/env bash

ffmpegcmd="$(command -v ffmpeg 2>/dev/null)"

[ "$ffmpegcmd" ] || exit 1

for track in ./*.flac; do
    $ffmpegcmd -i "$track" -b:a 320k -qscale:a 0 "${track/%'flac'/'mp3'}"
done
