#!/usr/bin/env bash

if hash cuebreakpoints 2>/dev/null \
    && hash shnsplit 2>/dev/null \
    && hash cuetag 2>/dev/null
then
    cuebreakpoints *.cue | shnsplit -o flac *.flac
    cuetag *.cue split-track*.flac
else
    echo "Make sure you have installed: cuebreakpoints, shnsplit, cuetag."
fi
