#!/usr/bin/env bash

if command -v cuebreakpoints &> /dev/null \
    && command -v shnsplit &> /dev/null \
    && command -v cuetag.sh &> /dev/null
then
    cuebreakpoints ./*.cue | shnsplit -o flac ./*.flac
    cuetag.sh ./*.cue split-track*.flac
else
    echo "Make sure you have installed: cuebreakpoints, shnsplit, cuetag.sh."
fi
