#!/usr/bin/env bash

URI="$1"
FRAG="${URI#*://}"
FRAG="${FRAG#*@}"
FRAG="${FRAG%.git}"

# check if url begins with schema section like ssh://
if [[ "$URI" =~ ^[A-Za-z]+:// ]] ; then
    # for URI-like urls
    URI_HOST="${FRAG%%/*}"
    URI_HOST="${URI_HOST%%\:*}"
    URI_PATH="${FRAG#*/}"
else
    # for scp-like urls
    URI_HOST="${FRAG%%\:*}"
    URI_PATH="${FRAG#*\:}"
fi

git clone "$URI" "$HOME/${GIT_CLONES_DIR:-Clones}/$URI_HOST/$URI_PATH"
