#!/usr/bin/env bash

function ku_init {
    case "$1" in
    bash)
        cat <<EOF
export _NO_NEWLINE=1
function prompt_ku_precmd {
    PS1="\$(ku prompt)"
    [ "\$_NO_NEWLINE" ] && unset _NO_NEWLINE
}
PROMPT_COMMAND+=('prompt_ku_precmd')
PROMPT_COMMAND+=('ku title bash')
EOF
        ;;
    zsh)
        cat <<EOF
export _NO_NEWLINE=1
function prompt_ku_precmd {
    PROMPT="\$(ku prompt)"
    [ "\$_NO_NEWLINE" ] && unset _NO_NEWLINE
}
autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_ku_precmd
EOF
        ;;
    *)
        exit 1
        ;;
    esac
}

function ku_title {
    case "$1" in
    bash)
        echo -en "\033]0;$1 $(pwd)\007"
        ;;
    zsh)
        echo -en "\e]0;$1 $(pwd)\a"
        ;;
    *)
        exit 1
        ;;
    esac
}

function ku_prompt {
    bold="$(tput bold)"
    red="$(tput setaf 1)"
    cyn="$(tput setaf 6)"
    reset="$(tput sgr0)"

    prompt="$reset"

    ### New line
    if [ -z "$_NO_NEWLINE" ]; then
        prompt+=$'\n'
    fi
    prompt+=" "

    ### Path to working dir
    prompt+="$bold$cyn$(ku_prompt_pwd)$reset "

    ### Git
    # git="$(prompt-git)"
    # if [ -n "$git" ]; then
    #     prompt+="$bold$blu$git$reset "
    # fi
    # prompt+=$'\n'
    # prompt+=" "

    ### Sign
    if [ "$(id -u)" -eq 0 ]; then
        prompt+="$bold$red$(ku_prompt_sign)$reset "
    else
        prompt+="$bold$(ku_prompt_sign)$reset "
    fi

    echo -n "$prompt"
}

function ku_prompt_pwd {
    [ -z "$PWD" ] && PWD="$(pwd)"
    case "$PWD" in
    "$HOME")
        echo -n '~'
        ;;
    "$HOME"/*/*)
        echo -n "${PWD#"${PWD%/*/*}/"}"
        ;;
    "$HOME"/*)
        echo -n ~/"${PWD##*/}"
        ;;
    *)
        echo -n "${PWD#"${PWD%/*/*}/"}"
        ;;
    esac
}

function ku_prompt_sign {
    if [ "$(id -u)" -eq 0 ]; then
        echo -n "#"
    else
        echo -n ">"
    fi
}

case "$1" in
prompt)
    ku_prompt "$2"
    ;;
title)
    ku_title "$2"
    ;;
init)
    ku_init "$2"
    ;;
*)
    exit 1
    ;;
esac
