#!/usr/bin/env bash

function _ku_shell {
    if [ -n "$ZSH_VERSION" ]; then
        /usr/bin/echo -n 'zsh'
    elif [ -n "$BASH_VERSION" ]; then
        /usr/bin/echo -n 'bash'
    fi
}

function _ku_init {
    case "$(_ku_shell)" in
    bash)
        cat <<EOF
export _NO_NEWLINE=1
function prompt_ku_precmd {
    PS1="\$(ku prompt)"
    [ -n "\$_NO_NEWLINE" ] && unset _NO_NEWLINE
}
PROMPT_COMMAND+=('prompt_ku_precmd')
PROMPT_COMMAND+=('ku title')
EOF
        ;;
    zsh)
        cat <<EOF
export _NO_NEWLINE=1
function prompt_ku_precmd {
    PROMPT="\$(ku prompt)"
    [ -n "\$_NO_NEWLINE" ] && unset _NO_NEWLINE
}
autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_ku_precmd
EOF
        ;;
    *)
        exit 1
        ;;
    esac
}

function _ku_title {
    case "$(_ku_shell)" in
    bash)
        /usr/bin/echo -en "\033]0;$1 $(pwd)\007"
        ;;
    zsh)
        /usr/bin/echo -en "\e]0;$1 $(pwd)\a"
        ;;
    *)
        exit 1
        ;;
    esac
}

function _ku_prompt {
    BLD=""
    RED=""
    CYN=""
    RST=""
    case "$(_ku_shell)" in
    bash)
        BLD="\[$(tput bold)\]"
        RST="\[$(tput sgr0)\]"
        RED="\[$(tput setaf 1)\]"
        CYN="\[$(tput setaf 6)\]"
        ;;
    zsh)
        BLD="$(tput bold)"
        RST="$(tput sgr0)"
        RED="$(tput setaf 1)"
        CYN="$(tput setaf 6)"
        ;;
    esac

    prompt="$RST"

    ### New line
    if [ -z "$_NO_NEWLINE" ]; then
        prompt+=$'\n'
    fi
    prompt+=' '

    ### Path to working dir
    prompt+="$BLD$CYN$(_ku_prompt_pwd)$RST"
    prompt+=' '

    ### Git
    # git="$(prompt-git)"
    # if [ -n "$git" ]; then
    #     prompt+="$BLD$blu$git$RST"
    # fi
    # prompt+=' '
    #
    # prompt+=$'\n'
    # prompt+=' '

    ### Sign
    if [ "$(id -u)" -eq 0 ]; then
        prompt+="$BLD$RED$(_ku_prompt_sign)$RST"
    else
        prompt+="$BLD$(_ku_prompt_sign)$RST"
    fi
    prompt+=' '

    /usr/bin/echo -n "$prompt"
}

function _ku_prompt_pwd {
    [ -z "$PWD" ] && PWD="$(pwd)"
    case "$PWD" in
    "$HOME")
        /usr/bin/echo -n '~'
        ;;
    "$HOME"/*/*)
        /usr/bin/echo -n "${PWD#"${PWD%/*/*}/"}"
        ;;
    "$HOME"/*)
        /usr/bin/echo -n '~'/
        /usr/bin/echo -n "${PWD##*/}"
        ;;
    *)
        /usr/bin/echo -n "${PWD#"${PWD%/*/*}/"}"
        ;;
    esac
}

function _ku_prompt_sign {
    if [ "$(id -u)" -eq 0 ]; then
        /usr/bin/echo -n '#'
    else
        /usr/bin/echo -n '>'
    fi
}

case "$1" in
prompt)
    _ku_prompt "$2"
    ;;
title)
    _ku_title "$2"
    ;;
init)
    _ku_init "$2"
    ;;
*)
    exit 1
    ;;
esac
