#!/usr/bin/env bash

function ku::main {
    case "$1" in
        'prompt')
            ku::validate "$2"
            ku::prompt "$2"
            ;;
        'title')
            ku::validate "$2"
            ku::title "$2"
            ;;
        *)
            exit 0
            ;;
    esac
}

function ku::validate {
    case "$1" in
        'bash'|'zsh') ;;
        *) exit 0 ;;
    esac
}

function ku::prompt {
    red=''
    grn=''
    blu=''
    cyn=''
    rst=''
    case "$1" in
        'bash')
            # bright colors
            red='\[\e[1;31m\]'
            grn='\[\e[1;32m\]'
            blu='\[\e[1;34m\]'
            cyn='\[\e[1;36m\]'
            rst='\[\e[0m\]'
            ;;
        'zsh')
            # bright colors
            red='%B%F{1}'
            grn='%B%F{2}'
            blu='%B%F{4}'
            cyn='%B%F{6}'
            rst='%f%b'
            ;;
    esac

    prompt="$rst"

    if [ -z "$_NO_NEWLINE" ]; then
        prompt+=$'\n'
    fi

    prompt+="${blu}$(ku::segment::pwd)${rst} "

    git="$(prompt-git)"
    if [ -n "$git" ]; then
        prompt+="${cyn}$git${rst} "
    fi

    prompt+=$'\n'

    sign="$(ku::segment::sign "$1" )"
    if [ "$sign" = '#' ]; then
        prompt+="${red}$sign${rst} "
    else
        prompt+="${grn}$sign${rst} "
    fi

    echo -n "$prompt"
}

function ku::title {
    case "$1" in
        'bash')
            echo -en "\033]0;$1 $(pwd)\007"
            ;;
        'zsh')
            echo -en "\e]0;$1 $(pwd)\a"
            ;;
    esac
}

function ku::segment::pwd {
    local pwd
    pwd="$(pwd)"
    case "$pwd" in
        "$HOME")
            echo -n '~'
            ;;
        "$HOME"/*/*)
            echo -n "${pwd#"${pwd%/*/*}/"}"
            ;;
        "$HOME"/*)
            echo -n ~/"${pwd##*/}"
            ;;
        *)
            echo -n "${pwd#"${pwd%/*/*}/"}"
            ;;
    esac
}

function ku::segment::sign {
    if [ "$(id -u)" -eq 0 ]; then
        echo -n "#"
    else
        case "$1" in
            'bash')
                echo -n "\$"
                ;;
            'zsh')
                echo -n "%%"
                ;;
        esac
    fi
}

ku::main "$@"
