#!/usr/bin/env bash

ffmpegcmd="$(command -v ffmpeg 2>/dev/null)"

[ "$ffmpegcmd" ] || exit 1

for track in ./*.m4a; do
    $ffmpegcmd -i "$track" -acodec libmp3lame -b:a 320k -qscale:a 0 "${track/%'m4a'/'mp3'}"
done
