#!/usr/bin/env bash

if hash ffmpeg 2>/dev/null; then
    for a in ./*.m4a; do
        ffmpeg -i "$a" -acodec libmp3lame -b:a 320k -qscale:a 0 "${a[@]/%m4a/mp3}"
    done
else
    echo "ffmpeg: Command not found..."
fi
