#!/usr/bin/env bash

[ -z "$1" ] && echo "Usage: $0 ARCHIVE_TYPE FILENAME" && exit 1

[ -e "$2" ] || $(echo "Invalid file: '$2'" && exit 1)

case "$1" in
    tar)
        tar -vp -cf "$2.tar" "$2" ;;
    tgz)
        tar -v -czf "$2.tar.gz" "$2" ;;
    tbz)
        tar -v -cjf "$2.tar.bz2" "$2" ;;
    gz)
        gzip -c -9 -n "$2" > "$2.gz" ;;
    bz2)
        bzip "$2" ;;
    zip)
        zip -r "$2.zip" "$2" ;;
    7z)
        7z a "$2.7z" "$2" ;;
    rar)
        rar a "$2.rar" "$2" ;;
    *)
        echo "Unknown archive type: '$1'" && exit 1 ;;
esac
