#!/usr/bin/env bash

STATE_FILE=${STATE_FILE:-/tmp/pulse-echo-cancel}

pactlcmd="$(command -v pactl 2>/dev/null)"

[ "$pactlcmd" ] || exit 1

if [ ! -f "$STATE_FILE" ]; then
    /usr/bin/echo "Enabled echo cancel module"
    $pactlcmd load-module module-echo-cancel > "$STATE_FILE"
else
    /usr/bin/echo "Disabled echo cancel module"
    $pactlcmd unload-module module-echo-cancel
    /usr/bin/rm "$STATE_FILE"
fi
