#!/usr/bin/env bash

STATE_FILE=/tmp/pulse-echo-cancel

if command -v pactl &> /dev/null && [ ! -f "$STATE_FILE" ]; then
    echo "Enabled echo cancel module"
    pactl load-module module-echo-cancel > "$STATE_FILE"
else
    echo "Disabled echo cancel module"
    pactl unload-module module-echo-cancel
    rm "$STATE_FILE"
fi
