#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 FILENAME"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Invalid file: '$1'"
    exit 1
fi

case "$1" in
    *.tar)
        tar -v -xf "$1"
        ;;
    *.tar.gz|*.tgz)
        tar -v -xzf "$1"
        ;;
    *.tar.bz2|.tar.bzip2|*.tbz2|.tb2|*.tar.bz|*.tbz)
        tar -v -xjf "$1"
        ;;
    *.tar.xz)
        tar -v -xJf "$1"
        ;;
    *.gz)
        gunzip "$1"
        ;;
    *.bz2|*.bz)
        bunzip2 "$1"
        ;;
    *.zip|*.cbz)
        unzip "$1"
        ;;
    *.rar|*.cbr)
        unrar x "$1"
        ;;
    *.7z)
        7z x "$1"
        ;;
    *)
        echo "Unknown file type: '$1'"
        exit 1
        ;;
esac
